
# Site settings
title: Chinthan Bhat
email: chinthanbhat@gmail.com
description: > 
  My test site.
baseurl: "/chinthanbhat" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  chinthanbhat

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
